name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          skip-cache: true

      - name: Lint Code
        run: golangci-lint run ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Unit Tests with Coverage
        run: |
          mkdir -p test-reports
          gotestsum --format=short-verbose --junitfile=test-reports/unit-test-report.xml -- -coverprofile=test-reports/coverage.txt ./...

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test-reports/coverage.txt
          flags: unittests
          fail_ci_if_error: true
          verbose: true
